### ISSUE TITLE
Cycling backwards through light stages

### ISSUE THREAD

**Issue by Cj24** [TheMaybeast/DLS#10]
Rather than only being able to cycle through the light stages normally, it would be useful to also be able to cycle through them backwards.
This could be implemented like in ELS, where you press Alt+J (Modifier key + Switch key) to switch to the previous stage.

Additionally, this feature could also be added for the traffic advisor patterns and direction switching.

**Comment by MOPC222** [comment]
Would be cool to have that as vehicle-specific property too, so for cars with it enabled pressing stage key would instantly switch to Stage 3

**Comment by Cj24** [comment]
> Would be cool to have that as vehicle-specific property too, so for cars with it enabled pressing stage key would instantly switch to Stage 3

That's indeed a nice idea. It could even be expanded, to allow customizing the order of stages and to skip specific stages per vehicle.

For example, there could be two options per car to customize the standard cycle (by default 0>1>2>3>0) and the modified (backwards) cycle I suggested (by default 0>3>2>1>0). This would also allow users to set up stages like ELS' jump mode (J to cycle 0>3>0, Alt+J to cycle 0>3>2>1>0).

The settings in the xml could for example be like this:
```
<LightStages>
	<StageSwitch>1,2,3</StageSwitch>
	<ModifiedStageSwitch>3,2,1</ModifiedStageSwitch>
</LightStages>
```

Though I'm not sure if this shouldn't be a separate issue, as having customizable light stages doesn't necessarily depend on the option to reverse the order.

**Comment by TheMaybeast** [comment]
As much of a cross-over this new suggestion has, I thinkg it'd be better to keep it in it's own issue due to some logistical problems that could arise from having them both in the same one.
