### ISSUE TITLE
Controller bug

### ISSUE THREAD

**Issue by Vincentsgm** [TheMaybeast/DLS#15]
When pressing DPadDown on the controller to turn on the sirens, we can't shut it off again. Also the UI doesn't show the siren being on when activating it that way.

**Comment by TheMaybeast** [comment]
I was unable to replicate this issue in-game, so more investigation is necessary. Before anything, ensure that:

1. You are utilizing the latest version of DLS (currently v1.0.2);
2. You are using the default DLS.ini file (reset to it if changed).

If problem persists, please elaborate on the following points:

- Does the problem occur only on DLS, only on non-DLS or on both?

- What model controller are you utilizing (Xbox vs Playstation)?

- Are you able to utilize the key (DPadDown) in-game with DLS unloaded? (To switch characters)

Also, please attach DLS.log, RagePluginHook.log and your DLS.ini file.

**Comment by TheMaybeast** [comment]
User reports not having the issue anymore. Closed.
